# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=2)),
                ('a_type', models.CharField(max_length=10)),
                ('start', models.CharField(max_length=30)),
                ('stop', models.CharField(max_length=30)),
                ('strand', models.CharField(max_length=2)),
                ('gene_id', models.CharField(max_length=30)),
                ('gene_name', models.CharField(max_length=30)),
                ('transcript_id', models.CharField(max_length=30)),
                ('transcript_name', models.CharField(max_length=30)),
                ('exon_id', models.CharField(max_length=30)),
                ('exon_number', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=2)),
                ('bind_start', models.CharField(max_length=30)),
                ('bind_stop', models.CharField(max_length=30)),
                ('mirna_name', models.CharField(max_length=20)),
                ('gene_id', models.CharField(max_length=30)),
                ('transcript_id', models.CharField(max_length=30)),
                ('bind_site', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=30)),
                ('strand', models.CharField(max_length=2)),
                ('relative_bind_start', models.CharField(max_length=20)),
                ('relative_bind_stop', models.CharField(max_length=20)),
                ('num_species_conserved', models.CharField(max_length=4)),
                ('species', models.CharField(max_length=200)),
                ('bind_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mirna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirna_name', models.CharField(max_length=30)),
                ('mirna_id', models.CharField(max_length=30)),
                ('mirna_sequence', models.CharField(max_length=30)),
            ],
        ),
    ]
