# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='transcript_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='transcript_name',
            field=models.CharField(max_length=40),
        ),
    ]
