# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_auto_20180409_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=2)),
                ('mirna_name', models.CharField(max_length=20)),
                ('transcript_id', models.CharField(max_length=30)),
                ('bind_start', models.CharField(max_length=30)),
                ('bind_stop', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='annotation',
            name='exon_id',
            field=models.CharField(default='null', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='exon_number',
            field=models.CharField(default='null', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='transcript_id',
            field=models.CharField(default='null', editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='transcript_name',
            field=models.CharField(default='null', editable=False, max_length=40),
        ),
    ]
