# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0006_auto_20180522_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='mirna_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_app.Mirna'),
        ),
    ]
