# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0008_auto_20180522_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mirna',
            name='id',
        ),
        migrations.AlterField(
            model_name='mirna',
            name='mirna_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
