# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0009_auto_20180522_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='mirna_name_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csv_app.Mirna'),
        ),
    ]
