# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 08:41
from __future__ import unicode_literals

from django.db import migrations

def link_mirnas(apps, schema_editor):
    Mirna = apps.get_model('csv_app', 'Mirna')
    Interaction = apps.get_model('csv_app', 'Interaction')
    for inter in Interaction.objects.all():
        mirna, created = Mirna.objects.get_or_create(mirna_name=interaction.mirna_name)
        inter.mirna_name_link = mirna
        inter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0010_interaction_mirna_name_link'),
    ]

    operations = [
        migrations.RunPython(link_mirnas),
    ]
