# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-07 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0017_auto_20180607_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychromosome',
            name='density',
            field=models.IntegerField(default=0),
        ),
    ]
