# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0019_auto_20180607_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='mirna_name_link',
        ),
        migrations.AddField(
            model_name='interaction',
            name='mirna_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csv_app.Mirna'),
        ),
    ]
