# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0020_auto_20180624_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='mirna_link',
            new_name='mir_link',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='mirna_name',
            field=models.CharField(max_length=33),
        ),
    ]
