# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0027_auto_20180723_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='score',
            field=models.FloatField(),
        ),
    ]
