# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0031_auto_20180729_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='mirna_con',
        ),
        migrations.AddField(
            model_name='interaction',
            name='mirna_conn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csv_app.Mirna'),
        ),
    ]
